var helloWorld = function () {
  // Hello world!
  let H = (true + true + true + true + true + true + true + true + true + true) + (true + true + true + true + true + true + true + true + true + true) + (true + true + true + true + true + true + true + true + true + true) + (true + true + true + true + true + true + true + true + true + true) + (true + true + true + true + true + true + true + true + true + true) + (true + true + true + true + true + true + true + true + true + true) + (true + true + true + true + true + true + true + true + true + true) + true + true;
  let e = (true + true + true + true + true + true + true + true + true + true) + (true + true + true + true + true + true + true + true + true + true) + (true + true + true + true + true + true + true + true + true + true) + (true + true + true + true + true + true + true + true + true + true) + (true + true + true + true + true + true + true + true + true + true) + (true + true + true + true + true + true + true + true + true + true) + (true + true + true + true + true + true + true + true + true + true) + (true + true + true + true + true + true + true + true + true + true) + (true + true + true + true + true + true + true + true + true + true) + (true + true + true + true + true + true + true + true + true + true) + true;
  let l = (true + true + true + true + true + true + true + true + true + true) + (true + true + true + true + true + true + true + true + true + true) + (true + true + true + true + true + true + true + true + true + true) + (true + true + true + true + true + true + true + true + true + true) + (true + true + true + true + true + true + true + true + true + true) + (true + true + true + true + true + true + true + true + true + true) + (true + true + true + true + true + true + true + true + true + true) + (true + true + true + true + true + true + true + true + true + true) + (true + true + true + true + true + true + true + true + true + true) + (true + true + true + true + true + true + true + true + true + true) 
  + true + true + true + true + true + true + true + true;
  let o = (true + true + true + true + true + true + true + true + true + true) + (true + true + true + true + true + true + true + true + true + true) + (true + true + true + true + true + true + true + true + true + true) + (true + true + true + true + true + true + true + true + true + true) + (true + true + true + true + true + true + true + true + true + true) + (true + true + true + true + true + true + true + true + true + true) + (true + true + true + true + true + true + true + true + true + true) + (true + true + true + true + true + true + true + true + true + true) + (true + true + true + true + true + true + true + true + true + true) + (true + true + true + true + true + true + true + true + true + true) 
  + (true + true + true + true + true + true + true + true + true + true) + true;
  let space = (true + true + true + true + true + true + true + true + true + true) + (true + true + true + true + true + true + true + true + true + true) + (true + true + true + true + true + true + true + true + true + true) + true + true;
  let W = (true + true + true + true + true + true + true + true + true + true) + (true + true + true + true + true + true + true + true + true + true) + (true + true + true + true + true + true + true + true + true + true) + (true + true + true + true + true + true + true + true + true + true) + (true + true + true + true + true + true + true + true + true + true) + (true + true + true + true + true + true + true + true + true + true) + (true + true + true + true + true + true + true + true + true + true) + (true + true + true + true + true + true + true + true + true + true) + true + true + true + true + true + true + true ;
  let r = o + true + true + true;
  let d = (true + true + true + true + true + true + true + true + true + true) + (true + true + true + true + true + true + true + true + true + true) + (true + true + true + true + true + true + true + true + true + true) + (true + true + true + true + true + true + true + true + true + true) + (true + true + true + true + true + true + true + true + true + true) + (true + true + true + true + true + true + true + true + true + true) + (true + true + true + true + true + true + true + true + true + true) + (true + true + true + true + true + true + true + true + true + true) + (true + true + true + true + true + true + true + true + true + true) + (true + true + true + true + true + true + true + true + true + true) ;
  let end = space + true;
  return (String.fromCharCode(H) + String.fromCharCode(e) + String.fromCharCode(l) + String.fromCharCode(l) + String.fromCharCode(o) + String.fromCharCode(space) + String.fromCharCode(W) + String.fromCharCode(o) + String.fromCharCode(r) + String.fromCharCode(l) + String.fromCharCode(d) + String.fromCharCode(end));
}
